#!/usr/bin/env python3
"""Проверяет libmcgen/tweaks.json и порождает из него:

  libmcgen/gen/mcgen_tweaks_table.h         таблица C `McTweakInfo MCGEN_TWEAK_TABLE[]` (+ индексы MCGEN_TWEAK_<ID>, стадии)
                                            для mcgen_tweak_count/mcgen_tweak_info и разбора значений в mcgen_world_new
  blender/mcgen_addon/core/tweaks.json      копия для аддона (ползунки «World Tweaks» строятся из неё динамически)

Использование:
    python3 libmcgen/gen_tweaks.py            # проверить и сгенерировать
    python3 libmcgen/gen_tweaks.py --check    # только проверить, что копии актуальны (код возврата 1, если нет)

Заголовок подключайте так (после mcgen.h):
    #include "mcgen_tweaks_table.h"           /* -I libmcgen/gen */
    n = MCGEN_TWEAK_COUNT; info = &MCGEN_TWEAK_TABLE[i]; stage = MCGEN_TWEAK_STAGE[i];
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, 'tweaks.json')
OUT_H = os.path.join(HERE, 'gen', 'mcgen_tweaks_table.h')
OUT_ADDON = os.path.join(ROOT, 'blender', 'mcgen_addon', 'core', 'tweaks.json')

STAGE_BITS = {'biomes': 1, 'terrain': 2, 'surface': 4, 'carvers': 8, 'features': 16, 'structures': 32}
ID_RE = re.compile(r'^[a-z][a-z0-9_]{0,47}$')
DIMS = {'overworld', 'nether', 'end'}


def load(path=SRC):
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def validate(doc):
    """Возвращает список ошибок (пустой — всё в порядке)."""
    err = []
    if doc.get('schema') != 1:
        err.append('schema != 1')
    stages = doc.get('stages', [])
    if stages != list(STAGE_BITS):
        err.append(f'stages должен быть {list(STAGE_BITS)}')
    groups = {g['id']: g for g in doc.get('groups', [])}
    for g in groups.values():
        for k in ('id', 'label', 'label_ru'):
            if not g.get(k):
                err.append(f'группа {g}: нет поля {k}')
    seen = set()
    for t in doc.get('tweaks', []):
        tid = t.get('id', '?')
        if not ID_RE.match(tid):
            err.append(f'{tid}: недопустимый id')
        if tid in seen:
            err.append(f'{tid}: дубликат')
        seen.add(tid)
        for k in ('label', 'label_ru', 'description', 'description_ru', 'group', 'type', 'stage', 'default',
                  'min', 'max', 'soft_min', 'soft_max', 'dimensions'):
            if k not in t:
                err.append(f'{tid}: нет поля {k}')
        if err and any(e.startswith(tid + ':') for e in err):
            continue
        if t['group'] not in groups:
            err.append(f'{tid}: неизвестная группа {t["group"]}')
        if t['type'] not in ('float', 'int', 'bool'):
            err.append(f'{tid}: type должен быть float/int/bool')
        if t['stage'] not in STAGE_BITS:
            err.append(f'{tid}: неизвестная стадия {t["stage"]}')
        if not set(t['dimensions']) <= DIMS or not t['dimensions']:
            err.append(f'{tid}: dimensions ⊄ {sorted(DIMS)}')
        lo, hi, slo, shi, d = t['min'], t['max'], t['soft_min'], t['soft_max'], t['default']
        if not (lo <= slo <= shi <= hi):
            err.append(f'{tid}: нарушено min <= soft_min <= soft_max <= max')
        if not (lo <= d <= hi):
            err.append(f'{tid}: default вне [min, max]')
        if t['type'] in ('int', 'bool'):
            for k in ('min', 'max', 'soft_min', 'soft_max', 'default'):
                if t[k] != int(t[k]):
                    err.append(f'{tid}: {k} должно быть целым')
        if t['type'] == 'bool' and (lo, hi) != (0, 1):
            err.append(f'{tid}: у bool min=0, max=1')
        if t['description'].endswith('.') or t['label'].endswith('.'):
            err.append(f'{tid}: английский текст без точки в конце (стиль Blender)')
    return err


def c_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def c_num(v):
    return repr(float(v))


def make_header(doc):
    tw = doc['tweaks']
    out = ['/* generated by libmcgen/gen_tweaks.py из libmcgen/tweaks.json — не редактировать */',
           '#ifndef MCGEN_TWEAKS_TABLE_H', '#define MCGEN_TWEAKS_TABLE_H',
           '#include "mcgen.h"', '', f'#define MCGEN_TWEAK_COUNT {len(tw)}', '']
    for i, t in enumerate(tw):
        out.append(f'#define MCGEN_TWEAK_{t["id"].upper()} {i}')
    out += ['', 'static const McTweakInfo MCGEN_TWEAK_TABLE[MCGEN_TWEAK_COUNT] = {']
    for t in tw:
        isint = 0 if t['type'] == 'float' else 1
        out.append('    { %s, %s, %s, %s, %s, %s, %s, %s, %s, %d },' % (
            c_str(t['id']), c_str(t['label']), c_str(t['group']), c_str(t['description']),
            c_num(t['default']), c_num(t['min']), c_num(t['max']), c_num(t['soft_min']), c_num(t['soft_max']), isint))
    out += ['};', '', '/* нижняя стадия (бит MC_STAGE_*), на которую влияет настройка */',
            'static const unsigned char MCGEN_TWEAK_STAGE[MCGEN_TWEAK_COUNT] = {']
    out.append('    ' + ', '.join(str(STAGE_BITS[t['stage']]) for t in tw))
    out += ['};', '', '/* измерения (бит 0 — overworld, 1 — nether, 2 — end), для которых настройка имеет смысл */',
            'static const unsigned char MCGEN_TWEAK_DIMS[MCGEN_TWEAK_COUNT] = {']
    bit = {'overworld': 1, 'nether': 2, 'end': 4}
    out.append('    ' + ', '.join(str(sum(bit[d] for d in t['dimensions'])) for t in tw))
    out += ['};', '', '#endif', '']
    return '\n'.join(out)


def main(argv):
    check = '--check' in argv
    doc = load()
    errs = validate(doc)
    if errs:
        print('tweaks.json: ошибки:\n  ' + '\n  '.join(errs))
        return 1
    header = make_header(doc)
    addon_text = open(SRC, encoding='utf-8').read()
    ok = True
    for path, text in ((OUT_H, header), (OUT_ADDON, addon_text)):
        cur = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if check:
            if cur != text:
                print(f'устарел: {os.path.relpath(path, ROOT)}')
                ok = False
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            if cur != text:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(text)
                print('записан', os.path.relpath(path, ROOT))
    if check:
        print('tweaks: копии актуальны' if ok else 'tweaks: запустите libmcgen/gen_tweaks.py')
        return 0 if ok else 1
    print(f'tweaks.json: {len(doc["tweaks"])} настроек, {len(doc["groups"])} групп — OK')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
