#!/usr/bin/env python3
"""Общие функции инструментов tools/gt: пути, версии, запуск ванильного сервера под flock, команды консоли.

Каталоги (все вне git, кроме tools/):
  run/pack-<V>/                 pack-каталог версии (данные датапака + reports/blocks.json), см. tools/make_pack.py
  run/gt/_srv/<V>/              «репозиторий бандлера» сервера (libraries/, versions/), общий для всех миров версии
  run/gt/<V>/<вариант>/<имя>/   один эталонный мир: server.properties, world/, server.log, manifest.json
  run/gt/packs/<V>/<вариант>/   собранный датапак варианта (кэш)
"""
import fcntl, json, os, re, subprocess, sys, time
from contextlib import contextmanager

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GT = f'{ROOT}/run/gt'
LOCK = '/tmp/mcgen-server.lock'
DIMS = {'overworld': 'overworld', 'nether': 'the_nether', 'the_nether': 'the_nether', 'end': 'the_end', 'the_end': 'the_end'}
DIM_SHORT = {'overworld': 'overworld', 'the_nether': 'nether', 'the_end': 'end'}
VERSIONS = ['26.1', '26.2', '26.3', '26.4-snapshot-2']


def pack_dir(version):
    return f'{ROOT}/run/pack-{version}'


def version_info(version):
    return json.load(open(f'{pack_dir(version)}/version.json'))


def data_format(version):
    """major формата датапака для pack.mcmeta (min_format = max_format = data_major)."""
    return int(version_info(version)['pack_version']['data_major'])


def server_jar(version):
    return f'{ROOT}/jars/server-{version}.jar'


def srv_home(version):
    p = f'{GT}/_srv/{version}'
    os.makedirs(p, exist_ok=True)
    return p


def read_props(path):
    kv = {}
    if os.path.exists(path):
        for l in open(path).read().splitlines():
            if '=' in l and not l.startswith('#'):
                k, v = l.split('=', 1)
                kv[k] = v
    return kv


def write_props(path, kv):
    with open(path, 'w') as f:
        f.write('#generated by tools/gt/common.py\n')
        for k, v in kv.items():
            f.write(f'{k}={v}\n')


@contextmanager
def server_lock(log=print):
    """Один ванильный сервер одновременно на всю машину (совместим с `flock /tmp/mcgen-server.lock`)."""
    with open(LOCK, 'a') as lf:
        t0 = time.monotonic()
        try:
            fcntl.flock(lf, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except OSError:
            log(f'ожидаю {LOCK} ...')
            fcntl.flock(lf, fcntl.LOCK_EX)
            log(f'блокировка получена через {time.monotonic() - t0:.0f} с')
        try:
            yield
        finally:
            fcntl.flock(lf, fcntl.LOCK_UN)


class Server:
    """Ванильный сервер как подпроцесс; команды в stdin, готовность по строке «Done (» в логе."""

    def __init__(self, version, run_dir, xmx='5g', extra_jvm=()):
        self.version, self.run_dir = version, run_dir
        self.log_path = f'{run_dir}/server.log'
        self.xmx, self.extra_jvm = xmx, list(extra_jvm)
        self.p = None

    def start(self, timeout=240):
        jar = server_jar(self.version)
        if not os.path.exists(jar):
            raise FileNotFoundError(jar)
        os.makedirs(self.run_dir, exist_ok=True)
        open(f'{self.run_dir}/eula.txt', 'w').write('eula=true\n')  # EULA принят пользователем (решение пользователя, см. задание W6)
        cmd = ['java', f'-Xmx{self.xmx}', '-XX:+UseParallelGC', f'-DbundlerRepoDir={srv_home(self.version)}', *self.extra_jvm, *os.environ.get('MCGEN_GT_JVM_EXTRA', '').split(), '-jar', jar, 'nogui']
        self.p = subprocess.Popen(cmd, cwd=self.run_dir, stdin=subprocess.PIPE, stdout=open(self.log_path, 'w'),
                                  stderr=subprocess.STDOUT, text=True, bufsize=1)
        t0 = time.monotonic()
        while time.monotonic() - t0 < timeout:
            time.sleep(1)
            if self.p.poll() is not None:
                raise RuntimeError(f'сервер завершился при старте (код {self.p.returncode}); см. {self.log_path}')
            if 'Done (' in self.log():
                time.sleep(1)
                return time.monotonic() - t0
        raise TimeoutError('сервер не стартовал')

    def log(self):
        try:
            return open(self.log_path, errors='ignore').read()
        except OSError:
            return ''

    def cmd(self, s):
        self.p.stdin.write(s + '\n')
        self.p.stdin.flush()

    def alive(self):
        return self.p is not None and self.p.poll() is None

    def stop(self, timeout=90):
        if not self.alive():
            return
        try:
            self.cmd('save-all flush'); time.sleep(2); self.cmd('stop')
            self.p.wait(timeout=timeout)
        except Exception:
            self.p.kill(); self.p.wait()
