"""Блок-уровневые факты игры 26.x, закодированные в Java (не в ресурсах). СГЕНЕРИРОВАНО dev/gen_blockprops.py — не править руками.

Имена без префикса `minecraft:`."""

# BlockBehaviour.Properties.noOcclusion(): блок не скрывает соседние грани
NO_OCCLUDE = frozenset((
    'acacia_button', 'acacia_door', 'acacia_hanging_sign', 'acacia_leaves', 'acacia_pressure_plate', 'acacia_sapling',
    'acacia_sign', 'acacia_trapdoor', 'acacia_wall_hanging_sign', 'acacia_wall_sign', 'activator_rail', 'air', 'allium',
    'amethyst_cluster', 'attached_melon_stem', 'attached_pumpkin_stem', 'azalea', 'azalea_leaves', 'azure_bluet',
    'bamboo', 'bamboo_button', 'bamboo_door', 'bamboo_hanging_sign', 'bamboo_pressure_plate', 'bamboo_sapling',
    'bamboo_sign', 'bamboo_trapdoor', 'bamboo_wall_hanging_sign', 'bamboo_wall_sign', 'barrier', 'beacon', 'beetroots',
    'big_dripleaf_stem', 'birch_button', 'birch_door', 'birch_hanging_sign', 'birch_leaves', 'birch_pressure_plate',
    'birch_sapling', 'birch_sign', 'birch_trapdoor', 'birch_wall_hanging_sign', 'birch_wall_sign', 'black_banner',
    'black_bed', 'black_candle', 'black_shulker_box', 'black_stained_glass', 'black_stained_glass_pane',
    'black_wall_banner', 'blue_banner', 'blue_bed', 'blue_candle', 'blue_orchid', 'blue_shulker_box',
    'blue_stained_glass', 'blue_stained_glass_pane', 'blue_wall_banner', 'brain_coral', 'brain_coral_fan',
    'brain_coral_wall_fan', 'brewing_stand', 'brown_banner', 'brown_bed', 'brown_candle', 'brown_mushroom',
    'brown_shulker_box', 'brown_stained_glass', 'brown_stained_glass_pane', 'brown_wall_banner', 'bubble_column',
    'bubble_coral', 'bubble_coral_fan', 'bubble_coral_wall_fan', 'bush', 'cactus_flower', 'campfire', 'candle',
    'carrots', 'cauldron', 'cave_air', 'cave_vines', 'cave_vines_plant', 'cherry_button', 'cherry_door',
    'cherry_hanging_sign', 'cherry_leaves', 'cherry_pressure_plate', 'cherry_sapling', 'cherry_sign', 'cherry_trapdoor',
    'cherry_wall_hanging_sign', 'cherry_wall_sign', 'chorus_flower', 'chorus_plant', 'closed_eyeblossom', 'cobweb',
    'cocoa', 'conduit', 'copper_bars', 'copper_chain', 'copper_door', 'copper_golem_statue', 'copper_grate',
    'copper_lantern', 'copper_torch', 'copper_trapdoor', 'copper_wall_torch', 'cornflower', 'creeper_head',
    'crimson_button', 'crimson_door', 'crimson_fungus', 'crimson_hanging_sign', 'crimson_pressure_plate',
    'crimson_roots', 'crimson_sign', 'crimson_trapdoor', 'crimson_wall_hanging_sign', 'crimson_wall_sign', 'cyan_banner',
    'cyan_bed', 'cyan_candle', 'cyan_shulker_box', 'cyan_stained_glass', 'cyan_stained_glass_pane', 'cyan_wall_banner',
    'dandelion', 'dark_oak_button', 'dark_oak_door', 'dark_oak_hanging_sign', 'dark_oak_leaves',
    'dark_oak_pressure_plate', 'dark_oak_sapling', 'dark_oak_sign', 'dark_oak_trapdoor', 'dark_oak_wall_hanging_sign',
    'dark_oak_wall_sign', 'dead_brain_coral', 'dead_brain_coral_fan', 'dead_brain_coral_wall_fan', 'dead_bubble_coral',
    'dead_bubble_coral_fan', 'dead_bubble_coral_wall_fan', 'dead_bush', 'dead_fire_coral', 'dead_fire_coral_fan',
    'dead_fire_coral_wall_fan', 'dead_horn_coral', 'dead_horn_coral_fan', 'dead_horn_coral_wall_fan', 'dead_tube_coral',
    'dead_tube_coral_fan', 'dead_tube_coral_wall_fan', 'decorated_pot', 'detector_rail', 'dragon_egg', 'dragon_head',
    'dried_ghast', 'end_gateway', 'end_portal', 'end_rod', 'exposed_copper_bars', 'exposed_copper_chain',
    'exposed_copper_door', 'exposed_copper_golem_statue', 'exposed_copper_grate', 'exposed_copper_lantern',
    'exposed_copper_trapdoor', 'exposed_lightning_rod', 'fern', 'fire', 'fire_coral', 'fire_coral_fan',
    'fire_coral_wall_fan', 'firefly_bush', 'flower_pot', 'flowering_azalea', 'flowering_azalea_leaves', 'frogspawn',
    'frosted_ice', 'glass', 'glass_pane', 'glow_lichen', 'golden_dandelion', 'gray_banner', 'gray_bed', 'gray_candle',
    'gray_shulker_box', 'gray_stained_glass', 'gray_stained_glass_pane', 'gray_wall_banner', 'green_banner', 'green_bed',
    'green_candle', 'green_shulker_box', 'green_stained_glass', 'green_stained_glass_pane', 'green_wall_banner',
    'hanging_roots', 'heavy_weighted_pressure_plate', 'honey_block', 'hopper', 'horn_coral', 'horn_coral_fan',
    'horn_coral_wall_fan', 'ice', 'iron_bars', 'iron_chain', 'iron_door', 'iron_trapdoor', 'jungle_button',
    'jungle_door', 'jungle_hanging_sign', 'jungle_leaves', 'jungle_pressure_plate', 'jungle_sapling', 'jungle_sign',
    'jungle_trapdoor', 'jungle_wall_hanging_sign', 'jungle_wall_sign', 'kelp', 'kelp_plant', 'ladder', 'lantern',
    'large_amethyst_bud', 'large_fern', 'lava', 'lava_cauldron', 'leaf_litter', 'lever', 'light', 'light_blue_banner',
    'light_blue_bed', 'light_blue_candle', 'light_blue_shulker_box', 'light_blue_stained_glass',
    'light_blue_stained_glass_pane', 'light_blue_wall_banner', 'light_gray_banner', 'light_gray_bed',
    'light_gray_candle', 'light_gray_shulker_box', 'light_gray_stained_glass', 'light_gray_stained_glass_pane',
    'light_gray_wall_banner', 'light_weighted_pressure_plate', 'lightning_rod', 'lilac', 'lily_of_the_valley',
    'lily_pad', 'lime_banner', 'lime_bed', 'lime_candle', 'lime_shulker_box', 'lime_stained_glass',
    'lime_stained_glass_pane', 'lime_wall_banner', 'magenta_banner', 'magenta_bed', 'magenta_candle',
    'magenta_shulker_box', 'magenta_stained_glass', 'magenta_stained_glass_pane', 'magenta_wall_banner',
    'mangrove_button', 'mangrove_door', 'mangrove_hanging_sign', 'mangrove_leaves', 'mangrove_pressure_plate',
    'mangrove_propagule', 'mangrove_roots', 'mangrove_sign', 'mangrove_trapdoor', 'mangrove_wall_hanging_sign',
    'mangrove_wall_sign', 'medium_amethyst_bud', 'melon_stem', 'moving_piston', 'nether_portal', 'nether_sprouts',
    'nether_wart', 'oak_button', 'oak_door', 'oak_hanging_sign', 'oak_leaves', 'oak_pressure_plate', 'oak_sapling',
    'oak_sign', 'oak_trapdoor', 'oak_wall_hanging_sign', 'oak_wall_sign', 'open_eyeblossom', 'orange_banner',
    'orange_bed', 'orange_candle', 'orange_poplar_leaves', 'orange_shulker_box', 'orange_stained_glass',
    'orange_stained_glass_pane', 'orange_tulip', 'orange_wall_banner', 'oxeye_daisy', 'oxidized_copper_bars',
    'oxidized_copper_chain', 'oxidized_copper_door', 'oxidized_copper_golem_statue', 'oxidized_copper_grate',
    'oxidized_copper_lantern', 'oxidized_copper_trapdoor', 'oxidized_lightning_rod', 'pale_hanging_moss',
    'pale_moss_carpet', 'pale_oak_button', 'pale_oak_door', 'pale_oak_hanging_sign', 'pale_oak_leaves',
    'pale_oak_pressure_plate', 'pale_oak_sapling', 'pale_oak_sign', 'pale_oak_trapdoor', 'pale_oak_wall_hanging_sign',
    'pale_oak_wall_sign', 'peony', 'piglin_head', 'pink_banner', 'pink_bed', 'pink_candle', 'pink_petals',
    'pink_shulker_box', 'pink_stained_glass', 'pink_stained_glass_pane', 'pink_tulip', 'pink_wall_banner',
    'pitcher_crop', 'pitcher_plant', 'player_head', 'pointed_dripstone', 'polished_blackstone_button',
    'polished_blackstone_pressure_plate', 'poplar_button', 'poplar_door', 'poplar_hanging_sign', 'poplar_pressure_plate',
    'poplar_sapling', 'poplar_sign', 'poplar_trapdoor', 'poplar_wall_hanging_sign', 'poplar_wall_sign', 'poppy',
    'potatoes', 'potted_acacia_sapling', 'potted_allium', 'potted_azalea_bush', 'potted_azure_bluet', 'potted_bamboo',
    'potted_birch_sapling', 'potted_blue_orchid', 'potted_brown_mushroom', 'potted_cactus', 'potted_cherry_sapling',
    'potted_closed_eyeblossom', 'potted_cornflower', 'potted_crimson_fungus', 'potted_crimson_roots', 'potted_dandelion',
    'potted_dark_oak_sapling', 'potted_dead_bush', 'potted_fern', 'potted_flowering_azalea_bush',
    'potted_golden_dandelion', 'potted_jungle_sapling', 'potted_lily_of_the_valley', 'potted_mangrove_propagule',
    'potted_oak_sapling', 'potted_open_eyeblossom', 'potted_orange_tulip', 'potted_oxeye_daisy',
    'potted_pale_oak_sapling', 'potted_pink_tulip', 'potted_poplar_sapling', 'potted_poppy', 'potted_red_mushroom',
    'potted_red_tulip', 'potted_spruce_sapling', 'potted_torchflower', 'potted_warped_fungus', 'potted_warped_roots',
    'potted_white_tulip', 'potted_wither_rose', 'powder_snow', 'powder_snow_cauldron', 'powered_rail', 'pumpkin_stem',
    'purple_banner', 'purple_bed', 'purple_candle', 'purple_shulker_box', 'purple_stained_glass',
    'purple_stained_glass_pane', 'purple_wall_banner', 'rail', 'red_banner', 'red_bed', 'red_candle', 'red_mushroom',
    'red_poplar_leaves', 'red_shrub', 'red_shulker_box', 'red_stained_glass', 'red_stained_glass_pane', 'red_tulip',
    'red_wall_banner', 'redstone_torch', 'redstone_wall_torch', 'redstone_wire', 'resin_clump', 'rose_bush',
    'scaffolding', 'sculk_vein', 'sea_pickle', 'seagrass', 'shelf_mushroom', 'short_dry_grass', 'short_grass',
    'shulker_box', 'skeleton_skull', 'slime_block', 'small_amethyst_bud', 'small_dripleaf', 'sniffer_egg',
    'soul_campfire', 'soul_fire', 'soul_lantern', 'soul_torch', 'soul_wall_torch', 'spawner', 'spore_blossom',
    'spruce_button', 'spruce_door', 'spruce_hanging_sign', 'spruce_leaves', 'spruce_pressure_plate', 'spruce_sapling',
    'spruce_sign', 'spruce_trapdoor', 'spruce_wall_hanging_sign', 'spruce_wall_sign', 'stone_button',
    'stone_pressure_plate', 'straw_bed', 'structure_void', 'sugar_cane', 'sulfur_spike', 'sunflower', 'sweet_berry_bush',
    'tall_dry_grass', 'tall_grass', 'tall_seagrass', 'test_instance_block', 'tinted_glass', 'torch', 'torchflower',
    'torchflower_crop', 'trial_spawner', 'tripwire', 'tripwire_hook', 'tube_coral', 'tube_coral_fan',
    'tube_coral_wall_fan', 'turtle_egg', 'twisting_vines', 'twisting_vines_plant', 'vault', 'vine', 'void_air',
    'wall_torch', 'warped_button', 'warped_door', 'warped_fungus', 'warped_hanging_sign', 'warped_pressure_plate',
    'warped_roots', 'warped_sign', 'warped_trapdoor', 'warped_wall_hanging_sign', 'warped_wall_sign', 'water',
    'water_cauldron', 'waxed_copper_bars', 'waxed_copper_chain', 'waxed_copper_door', 'waxed_copper_golem_statue',
    'waxed_copper_grate', 'waxed_copper_lantern', 'waxed_copper_trapdoor', 'waxed_exposed_copper_bars',
    'waxed_exposed_copper_chain', 'waxed_exposed_copper_door', 'waxed_exposed_copper_golem_statue',
    'waxed_exposed_copper_grate', 'waxed_exposed_copper_lantern', 'waxed_exposed_copper_trapdoor',
    'waxed_exposed_lightning_rod', 'waxed_lightning_rod', 'waxed_oxidized_copper_bars', 'waxed_oxidized_copper_chain',
    'waxed_oxidized_copper_door', 'waxed_oxidized_copper_golem_statue', 'waxed_oxidized_copper_grate',
    'waxed_oxidized_copper_lantern', 'waxed_oxidized_copper_trapdoor', 'waxed_oxidized_lightning_rod',
    'waxed_weathered_copper_bars', 'waxed_weathered_copper_chain', 'waxed_weathered_copper_door',
    'waxed_weathered_copper_golem_statue', 'waxed_weathered_copper_grate', 'waxed_weathered_copper_lantern',
    'waxed_weathered_copper_trapdoor', 'waxed_weathered_lightning_rod', 'weathered_copper_bars',
    'weathered_copper_chain', 'weathered_copper_door', 'weathered_copper_golem_statue', 'weathered_copper_grate',
    'weathered_copper_lantern', 'weathered_copper_trapdoor', 'weathered_lightning_rod', 'weeping_vines',
    'weeping_vines_plant', 'wheat', 'white_banner', 'white_bed', 'white_candle', 'white_shulker_box',
    'white_stained_glass', 'white_stained_glass_pane', 'white_tulip', 'white_wall_banner', 'wildflowers', 'wither_rose',
    'wither_skeleton_skull', 'yellow_banner', 'yellow_bed', 'yellow_candle', 'yellow_poplar_leaves',
    'yellow_shulker_box', 'yellow_stained_glass', 'yellow_stained_glass_pane', 'yellow_wall_banner', 'zombie_head',
))

# BlockState.isSolid() == false (учитывается жидкостью при расчёте высоты у берега)
NOT_SOLID = frozenset((
    'acacia_button', 'acacia_sapling', 'activator_rail', 'air', 'allium', 'attached_melon_stem', 'attached_pumpkin_stem',
    'azalea', 'azure_bluet', 'bamboo_button', 'beetroots', 'big_dripleaf', 'big_dripleaf_stem', 'birch_button',
    'birch_sapling', 'black_candle', 'black_carpet', 'blue_candle', 'blue_carpet', 'blue_orchid', 'brain_coral',
    'brain_coral_fan', 'brain_coral_wall_fan', 'brown_candle', 'brown_carpet', 'brown_mushroom', 'bubble_column',
    'bubble_coral', 'bubble_coral_fan', 'bubble_coral_wall_fan', 'bush', 'cactus_flower', 'candle', 'carrots',
    'cave_air', 'cave_vines', 'cave_vines_plant', 'cherry_button', 'cherry_sapling', 'chorus_flower', 'chorus_plant',
    'closed_eyeblossom', 'cocoa', 'comparator', 'copper_golem_statue', 'copper_torch', 'copper_wall_torch', 'cornflower',
    'creeper_head', 'creeper_wall_head', 'crimson_button', 'crimson_fungus', 'crimson_roots', 'cyan_candle',
    'cyan_carpet', 'dandelion', 'dark_oak_button', 'dark_oak_sapling', 'dead_bush', 'detector_rail', 'dragon_head',
    'dragon_wall_head', 'end_gateway', 'end_portal', 'end_rod', 'exposed_copper_golem_statue', 'fern', 'fire',
    'fire_coral', 'fire_coral_fan', 'fire_coral_wall_fan', 'firefly_bush', 'flower_pot', 'flowering_azalea', 'frogspawn',
    'glow_lichen', 'golden_dandelion', 'gray_candle', 'gray_carpet', 'green_candle', 'green_carpet', 'hanging_roots',
    'heavy_core', 'horn_coral', 'horn_coral_fan', 'horn_coral_wall_fan', 'jungle_button', 'jungle_sapling', 'kelp',
    'kelp_plant', 'ladder', 'large_fern', 'lava', 'leaf_litter', 'lever', 'light', 'light_blue_candle',
    'light_blue_carpet', 'light_gray_candle', 'light_gray_carpet', 'lilac', 'lily_of_the_valley', 'lily_pad',
    'lime_candle', 'lime_carpet', 'magenta_candle', 'magenta_carpet', 'mangrove_button', 'mangrove_propagule',
    'melon_stem', 'moss_carpet', 'nether_portal', 'nether_sprouts', 'nether_wart', 'oak_button', 'oak_sapling',
    'open_eyeblossom', 'orange_candle', 'orange_carpet', 'orange_tulip', 'oxeye_daisy', 'oxidized_copper_golem_statue',
    'pale_hanging_moss', 'pale_moss_carpet', 'pale_oak_button', 'pale_oak_sapling', 'peony', 'piglin_head',
    'piglin_wall_head', 'pink_candle', 'pink_carpet', 'pink_petals', 'pink_tulip', 'pitcher_crop', 'pitcher_plant',
    'player_head', 'player_wall_head', 'polished_blackstone_button', 'poplar_button', 'poplar_sapling', 'poppy',
    'potatoes', 'potted_acacia_sapling', 'potted_allium', 'potted_azalea_bush', 'potted_azure_bluet', 'potted_bamboo',
    'potted_birch_sapling', 'potted_blue_orchid', 'potted_brown_mushroom', 'potted_cactus', 'potted_cherry_sapling',
    'potted_closed_eyeblossom', 'potted_cornflower', 'potted_crimson_fungus', 'potted_crimson_roots', 'potted_dandelion',
    'potted_dark_oak_sapling', 'potted_dead_bush', 'potted_fern', 'potted_flowering_azalea_bush',
    'potted_golden_dandelion', 'potted_jungle_sapling', 'potted_lily_of_the_valley', 'potted_mangrove_propagule',
    'potted_oak_sapling', 'potted_open_eyeblossom', 'potted_orange_tulip', 'potted_oxeye_daisy',
    'potted_pale_oak_sapling', 'potted_pink_tulip', 'potted_poplar_sapling', 'potted_poppy', 'potted_red_mushroom',
    'potted_red_tulip', 'potted_spruce_sapling', 'potted_torchflower', 'potted_warped_fungus', 'potted_warped_roots',
    'potted_white_tulip', 'potted_wither_rose', 'powder_snow', 'powered_rail', 'pumpkin_stem', 'purple_candle',
    'purple_carpet', 'rail', 'red_candle', 'red_carpet', 'red_mushroom', 'red_shrub', 'red_tulip', 'redstone_torch',
    'redstone_wall_torch', 'redstone_wire', 'repeater', 'resin_clump', 'rose_bush', 'scaffolding', 'sea_pickle',
    'seagrass', 'shelf_mushroom', 'short_dry_grass', 'short_grass', 'skeleton_skull', 'skeleton_wall_skull',
    'small_dripleaf', 'snow', 'soul_fire', 'soul_torch', 'soul_wall_torch', 'spore_blossom', 'spruce_button',
    'spruce_sapling', 'stone_button', 'structure_void', 'sugar_cane', 'sunflower', 'sweet_berry_bush', 'tall_dry_grass',
    'tall_grass', 'tall_seagrass', 'torch', 'torchflower', 'torchflower_crop', 'tripwire', 'tripwire_hook', 'tube_coral',
    'tube_coral_fan', 'tube_coral_wall_fan', 'twisting_vines', 'twisting_vines_plant', 'vine', 'void_air', 'wall_torch',
    'warped_button', 'warped_fungus', 'warped_roots', 'water', 'waxed_copper_golem_statue',
    'waxed_exposed_copper_golem_statue', 'waxed_oxidized_copper_golem_statue', 'waxed_weathered_copper_golem_statue',
    'weathered_copper_golem_statue', 'weeping_vines', 'weeping_vines_plant', 'wheat', 'white_candle', 'white_carpet',
    'white_tulip', 'wildflowers', 'wither_rose', 'wither_skeleton_skull', 'wither_skeleton_wall_skull', 'yellow_candle',
    'yellow_carpet', 'zombie_head', 'zombie_wall_head',
))

# RenderShape.INVISIBLE (воздух, жидкости, барьер, свет, structure_void, …)
INVISIBLE = frozenset((
    'air', 'barrier', 'bubble_column', 'cave_air', 'end_gateway', 'end_portal', 'lava', 'light', 'moving_piston',
    'structure_void', 'void_air', 'water',
))

# блоки, у которых все состояния содержат воду-источник (морская трава, ламинария, столб пузырей)
ALWAYS_WATER = frozenset((
    'bubble_column', 'kelp', 'kelp_plant', 'seagrass', 'tall_seagrass',
))

# смещение модели (OffsetType): имя -> (1 = XZ | 2 = XYZ, макс. по горизонтали, макс. по вертикали) в блоках
OFFSET = {
    'allium': (1, 0.25, 0.2),
    'azure_bluet': (1, 0.25, 0.2),
    'bamboo': (1, 0.25, 0.2),
    'bamboo_sapling': (1, 0.25, 0.2),
    'blue_orchid': (1, 0.25, 0.2),
    'closed_eyeblossom': (1, 0.25, 0.2),
    'cornflower': (1, 0.25, 0.2),
    'crimson_roots': (1, 0.25, 0.2),
    'dandelion': (1, 0.25, 0.2),
    'fern': (2, 0.25, 0.2),
    'golden_dandelion': (1, 0.25, 0.2),
    'hanging_roots': (1, 0.25, 0.2),
    'large_fern': (1, 0.25, 0.2),
    'lilac': (1, 0.25, 0.2),
    'lily_of_the_valley': (1, 0.25, 0.2),
    'mangrove_propagule': (1, 0.25, 0.2),
    'nether_sprouts': (1, 0.25, 0.2),
    'open_eyeblossom': (1, 0.25, 0.2),
    'orange_tulip': (1, 0.25, 0.2),
    'oxeye_daisy': (1, 0.25, 0.2),
    'peony': (1, 0.25, 0.2),
    'pink_tulip': (1, 0.25, 0.2),
    'pitcher_plant': (1, 0.25, 0.2),
    'pointed_dripstone': (1, 0.125, 0.2),
    'poppy': (1, 0.25, 0.2),
    'red_tulip': (1, 0.25, 0.2),
    'rose_bush': (1, 0.25, 0.2),
    'short_dry_grass': (2, 0.25, 0.2),
    'short_grass': (2, 0.25, 0.2),
    'small_dripleaf': (2, 0.25, 0.1),
    'sulfur_spike': (1, 0.125, 0.2),
    'sunflower': (1, 0.25, 0.2),
    'tall_dry_grass': (2, 0.25, 0.2),
    'tall_grass': (1, 0.25, 0.2),
    'tall_seagrass': (1, 0.25, 0.2),
    'torchflower': (1, 0.25, 0.2),
    'warped_roots': (1, 0.25, 0.2),
    'white_tulip': (1, 0.25, 0.2),
    'wither_rose': (1, 0.25, 0.2),
}

# Block.skipRendering: H = HalfTransparentBlock (сосед того же блока), L = листва, B = IronBars/панели, P = порошковый снег,
# M = корни мангров, W = жидкость
SKIP = {
    'acacia_leaves': 'L',
    'azalea_leaves': 'L',
    'birch_leaves': 'L',
    'black_stained_glass': 'H',
    'black_stained_glass_pane': 'B',
    'blue_ice': 'H',
    'blue_stained_glass': 'H',
    'blue_stained_glass_pane': 'B',
    'brown_stained_glass': 'H',
    'brown_stained_glass_pane': 'B',
    'cherry_leaves': 'L',
    'copper_bars': 'B',
    'copper_grate': 'H',
    'cyan_stained_glass': 'H',
    'cyan_stained_glass_pane': 'B',
    'dark_oak_leaves': 'L',
    'exposed_copper_bars': 'B',
    'exposed_copper_grate': 'H',
    'flowering_azalea_leaves': 'L',
    'frosted_ice': 'H',
    'glass': 'H',
    'glass_pane': 'B',
    'gray_stained_glass': 'H',
    'gray_stained_glass_pane': 'B',
    'green_stained_glass': 'H',
    'green_stained_glass_pane': 'B',
    'honey_block': 'H',
    'ice': 'H',
    'iron_bars': 'B',
    'jungle_leaves': 'L',
    'lava': 'W',
    'light_blue_stained_glass': 'H',
    'light_blue_stained_glass_pane': 'B',
    'light_gray_stained_glass': 'H',
    'light_gray_stained_glass_pane': 'B',
    'lime_stained_glass': 'H',
    'lime_stained_glass_pane': 'B',
    'magenta_stained_glass': 'H',
    'magenta_stained_glass_pane': 'B',
    'mangrove_leaves': 'L',
    'mangrove_roots': 'M',
    'oak_leaves': 'L',
    'orange_poplar_leaves': 'L',
    'orange_stained_glass': 'H',
    'orange_stained_glass_pane': 'B',
    'oxidized_copper_bars': 'B',
    'oxidized_copper_grate': 'H',
    'pale_oak_leaves': 'L',
    'pink_stained_glass': 'H',
    'pink_stained_glass_pane': 'B',
    'powder_snow': 'P',
    'purple_stained_glass': 'H',
    'purple_stained_glass_pane': 'B',
    'red_poplar_leaves': 'L',
    'red_stained_glass': 'H',
    'red_stained_glass_pane': 'B',
    'slime_block': 'H',
    'spruce_leaves': 'L',
    'tinted_glass': 'H',
    'water': 'W',
    'waxed_copper_bars': 'B',
    'waxed_copper_grate': 'H',
    'waxed_exposed_copper_bars': 'B',
    'waxed_exposed_copper_grate': 'H',
    'waxed_oxidized_copper_bars': 'B',
    'waxed_oxidized_copper_grate': 'H',
    'waxed_weathered_copper_bars': 'B',
    'waxed_weathered_copper_grate': 'H',
    'weathered_copper_bars': 'B',
    'weathered_copper_grate': 'H',
    'white_stained_glass': 'H',
    'white_stained_glass_pane': 'B',
    'yellow_poplar_leaves': 'L',
    'yellow_stained_glass': 'H',
    'yellow_stained_glass_pane': 'B',
}

# имена блоков по классам Java (включая наследников)
CLASS_MEMBERS = {
    'FenceBlock': frozenset((
        'acacia_fence', 'bamboo_fence', 'birch_fence', 'cherry_fence', 'crimson_fence', 'dark_oak_fence',
        'jungle_fence', 'mangrove_fence', 'nether_brick_fence', 'oak_fence', 'pale_oak_fence', 'poplar_fence',
        'spruce_fence', 'warped_fence',
    )),
    'FenceGateBlock': frozenset((
        'acacia_fence_gate', 'bamboo_fence_gate', 'birch_fence_gate', 'cherry_fence_gate', 'crimson_fence_gate',
        'dark_oak_fence_gate', 'jungle_fence_gate', 'mangrove_fence_gate', 'oak_fence_gate', 'pale_oak_fence_gate',
        'poplar_fence_gate', 'spruce_fence_gate', 'warped_fence_gate',
    )),
    'IronBarsBlock': frozenset((
        'black_stained_glass_pane', 'blue_stained_glass_pane', 'brown_stained_glass_pane', 'copper_bars',
        'cyan_stained_glass_pane', 'exposed_copper_bars', 'glass_pane', 'gray_stained_glass_pane',
        'green_stained_glass_pane', 'iron_bars', 'light_blue_stained_glass_pane', 'light_gray_stained_glass_pane',
        'lime_stained_glass_pane', 'magenta_stained_glass_pane', 'orange_stained_glass_pane', 'oxidized_copper_bars',
        'pink_stained_glass_pane', 'purple_stained_glass_pane', 'red_stained_glass_pane', 'waxed_copper_bars',
        'waxed_exposed_copper_bars', 'waxed_oxidized_copper_bars', 'waxed_weathered_copper_bars',
        'weathered_copper_bars', 'white_stained_glass_pane', 'yellow_stained_glass_pane',
    )),
    'WallBlock': frozenset((
        'andesite_wall', 'blackstone_wall', 'brick_wall', 'cinnabar_brick_wall', 'cinnabar_wall',
        'cobbled_deepslate_wall', 'cobblestone_wall', 'deepslate_brick_wall', 'deepslate_tile_wall', 'diorite_wall',
        'end_stone_brick_wall', 'granite_wall', 'mossy_cobblestone_wall', 'mossy_stone_brick_wall', 'mud_brick_wall',
        'nether_brick_wall', 'polished_blackstone_brick_wall', 'polished_blackstone_wall', 'polished_cinnabar_wall',
        'polished_deepslate_wall', 'polished_sulfur_wall', 'polished_tuff_wall', 'prismarine_wall',
        'red_nether_brick_wall', 'red_sandstone_wall', 'resin_brick_wall', 'sandstone_wall', 'stone_brick_wall',
        'sulfur_brick_wall', 'sulfur_wall', 'tuff_brick_wall', 'tuff_wall',
    )),
    'StairBlock': frozenset((
        'acacia_stairs', 'andesite_stairs', 'bamboo_mosaic_stairs', 'bamboo_stairs', 'birch_stairs',
        'black_concrete_stairs', 'black_wool_stairs', 'blackstone_stairs', 'blue_concrete_stairs', 'blue_wool_stairs',
        'brick_stairs', 'brown_concrete_stairs', 'brown_wool_stairs', 'cherry_stairs', 'cinnabar_brick_stairs',
        'cinnabar_stairs', 'cobbled_deepslate_stairs', 'cobblestone_stairs', 'crimson_stairs', 'cut_copper_stairs',
        'cyan_concrete_stairs', 'cyan_wool_stairs', 'dark_oak_stairs', 'dark_prismarine_stairs',
        'deepslate_brick_stairs', 'deepslate_tile_stairs', 'diorite_stairs', 'end_stone_brick_stairs',
        'exposed_cut_copper_stairs', 'granite_stairs', 'gray_concrete_stairs', 'gray_wool_stairs',
        'green_concrete_stairs', 'green_wool_stairs', 'jungle_stairs', 'light_blue_concrete_stairs',
        'light_blue_wool_stairs', 'light_gray_concrete_stairs', 'light_gray_wool_stairs', 'lime_concrete_stairs',
        'lime_wool_stairs', 'magenta_concrete_stairs', 'magenta_wool_stairs', 'mangrove_stairs',
        'mossy_cobblestone_stairs', 'mossy_stone_brick_stairs', 'mud_brick_stairs', 'nether_brick_stairs',
        'oak_stairs', 'orange_concrete_stairs', 'orange_wool_stairs', 'oxidized_cut_copper_stairs', 'pale_oak_stairs',
        'pink_concrete_stairs', 'pink_wool_stairs', 'polished_andesite_stairs', 'polished_blackstone_brick_stairs',
        'polished_blackstone_stairs', 'polished_cinnabar_stairs', 'polished_deepslate_stairs',
        'polished_diorite_stairs', 'polished_granite_stairs', 'polished_sulfur_stairs', 'polished_tuff_stairs',
        'poplar_stairs', 'prismarine_brick_stairs', 'prismarine_stairs', 'purple_concrete_stairs',
        'purple_wool_stairs', 'purpur_stairs', 'quartz_stairs', 'red_concrete_stairs', 'red_nether_brick_stairs',
        'red_sandstone_stairs', 'red_wool_stairs', 'resin_brick_stairs', 'sandstone_stairs', 'smooth_quartz_stairs',
        'smooth_red_sandstone_stairs', 'smooth_sandstone_stairs', 'spruce_stairs', 'stone_brick_stairs',
        'stone_stairs', 'sulfur_brick_stairs', 'sulfur_stairs', 'tuff_brick_stairs', 'tuff_stairs', 'warped_stairs',
        'waxed_cut_copper_stairs', 'waxed_exposed_cut_copper_stairs', 'waxed_oxidized_cut_copper_stairs',
        'waxed_weathered_cut_copper_stairs', 'weathered_cut_copper_stairs', 'white_concrete_stairs',
        'white_wool_stairs', 'yellow_concrete_stairs', 'yellow_wool_stairs',
    )),
    'SlabBlock': frozenset((
        'acacia_slab', 'andesite_slab', 'bamboo_mosaic_slab', 'bamboo_slab', 'birch_slab', 'black_concrete_slab',
        'black_wool_slab', 'blackstone_slab', 'blue_concrete_slab', 'blue_wool_slab', 'brick_slab',
        'brown_concrete_slab', 'brown_wool_slab', 'cherry_slab', 'cinnabar_brick_slab', 'cinnabar_slab',
        'cobbled_deepslate_slab', 'cobblestone_slab', 'crimson_slab', 'cut_copper_slab', 'cut_red_sandstone_slab',
        'cut_sandstone_slab', 'cyan_concrete_slab', 'cyan_wool_slab', 'dark_oak_slab', 'dark_prismarine_slab',
        'deepslate_brick_slab', 'deepslate_tile_slab', 'diorite_slab', 'end_stone_brick_slab',
        'exposed_cut_copper_slab', 'granite_slab', 'gray_concrete_slab', 'gray_wool_slab', 'green_concrete_slab',
        'green_wool_slab', 'jungle_slab', 'light_blue_concrete_slab', 'light_blue_wool_slab',
        'light_gray_concrete_slab', 'light_gray_wool_slab', 'lime_concrete_slab', 'lime_wool_slab',
        'magenta_concrete_slab', 'magenta_wool_slab', 'mangrove_slab', 'mossy_cobblestone_slab',
        'mossy_stone_brick_slab', 'mud_brick_slab', 'nether_brick_slab', 'oak_slab', 'orange_concrete_slab',
        'orange_wool_slab', 'oxidized_cut_copper_slab', 'pale_oak_slab', 'petrified_oak_slab', 'pink_concrete_slab',
        'pink_wool_slab', 'polished_andesite_slab', 'polished_blackstone_brick_slab', 'polished_blackstone_slab',
        'polished_cinnabar_slab', 'polished_deepslate_slab', 'polished_diorite_slab', 'polished_granite_slab',
        'polished_sulfur_slab', 'polished_tuff_slab', 'poplar_slab', 'prismarine_brick_slab', 'prismarine_slab',
        'purple_concrete_slab', 'purple_wool_slab', 'purpur_slab', 'quartz_slab', 'red_concrete_slab',
        'red_nether_brick_slab', 'red_sandstone_slab', 'red_wool_slab', 'resin_brick_slab', 'sandstone_slab',
        'smooth_quartz_slab', 'smooth_red_sandstone_slab', 'smooth_sandstone_slab', 'smooth_stone_slab', 'spruce_slab',
        'stone_brick_slab', 'stone_slab', 'sulfur_brick_slab', 'sulfur_slab', 'tuff_brick_slab', 'tuff_slab',
        'warped_slab', 'waxed_cut_copper_slab', 'waxed_exposed_cut_copper_slab', 'waxed_oxidized_cut_copper_slab',
        'waxed_weathered_cut_copper_slab', 'weathered_cut_copper_slab', 'white_concrete_slab', 'white_wool_slab',
        'yellow_concrete_slab', 'yellow_wool_slab',
    )),
    'DoorBlock': frozenset((
        'acacia_door', 'bamboo_door', 'birch_door', 'cherry_door', 'copper_door', 'crimson_door', 'dark_oak_door',
        'exposed_copper_door', 'iron_door', 'jungle_door', 'mangrove_door', 'oak_door', 'oxidized_copper_door',
        'pale_oak_door', 'poplar_door', 'spruce_door', 'warped_door', 'waxed_copper_door', 'waxed_exposed_copper_door',
        'waxed_oxidized_copper_door', 'waxed_weathered_copper_door', 'weathered_copper_door',
    )),
    'TrapDoorBlock': frozenset((
        'acacia_trapdoor', 'bamboo_trapdoor', 'birch_trapdoor', 'cherry_trapdoor', 'copper_trapdoor',
        'crimson_trapdoor', 'dark_oak_trapdoor', 'exposed_copper_trapdoor', 'iron_trapdoor', 'jungle_trapdoor',
        'mangrove_trapdoor', 'oak_trapdoor', 'oxidized_copper_trapdoor', 'pale_oak_trapdoor', 'poplar_trapdoor',
        'spruce_trapdoor', 'warped_trapdoor', 'waxed_copper_trapdoor', 'waxed_exposed_copper_trapdoor',
        'waxed_oxidized_copper_trapdoor', 'waxed_weathered_copper_trapdoor', 'weathered_copper_trapdoor',
    )),
    'BedBlock': frozenset((
        'black_bed', 'blue_bed', 'brown_bed', 'cyan_bed', 'gray_bed', 'green_bed', 'light_blue_bed', 'light_gray_bed',
        'lime_bed', 'magenta_bed', 'orange_bed', 'pink_bed', 'purple_bed', 'red_bed', 'white_bed', 'yellow_bed',
    )),
    'DoublePlantBlock': frozenset((
        'large_fern', 'lilac', 'peony', 'pitcher_crop', 'pitcher_plant', 'rose_bush', 'small_dripleaf', 'sunflower',
        'tall_grass', 'tall_seagrass',
    )),
    'SnowLayerBlock': frozenset((
        'snow',
    )),
    'GrassBlock': frozenset((
        'grass_block',
    )),
    'ChorusPlantBlock': frozenset((
        'chorus_plant',
    )),
    'VineBlock': frozenset((
        'vine',
    )),
    'StemBlock': frozenset((
        'melon_stem', 'pumpkin_stem',
    )),
    'AttachedStemBlock': frozenset((
        'attached_melon_stem', 'attached_pumpkin_stem',
    )),
    'LeavesBlock': frozenset((
        'acacia_leaves', 'azalea_leaves', 'birch_leaves', 'cherry_leaves', 'dark_oak_leaves',
        'flowering_azalea_leaves', 'jungle_leaves', 'mangrove_leaves', 'oak_leaves', 'orange_poplar_leaves',
        'pale_oak_leaves', 'red_poplar_leaves', 'spruce_leaves', 'yellow_poplar_leaves',
    )),
    'PistonBaseBlock': frozenset((
        'piston', 'sticky_piston',
    )),
    'MultifaceBlock': frozenset((
        'glow_lichen', 'resin_clump', 'sculk_vein',
    )),
    'CarpetBlock': frozenset((
        'black_carpet', 'blue_carpet', 'brown_carpet', 'cyan_carpet', 'gray_carpet', 'green_carpet',
        'light_blue_carpet', 'light_gray_carpet', 'lime_carpet', 'magenta_carpet', 'moss_carpet', 'orange_carpet',
        'pink_carpet', 'purple_carpet', 'red_carpet', 'white_carpet', 'yellow_carpet',
    )),
    'FlowerBedBlock': frozenset((
        'pink_petals', 'wildflowers',
    )),
    'ChainBlock': frozenset((
        'copper_chain', 'exposed_copper_chain', 'iron_chain', 'oxidized_copper_chain', 'waxed_copper_chain',
        'waxed_exposed_copper_chain', 'waxed_oxidized_copper_chain', 'waxed_weathered_copper_chain',
        'weathered_copper_chain',
    )),
    'LayeredCauldronBlock': frozenset((
        'powder_snow_cauldron', 'water_cauldron',
    )),
    'AbstractCauldronBlock': frozenset((
        'cauldron', 'lava_cauldron', 'powder_snow_cauldron', 'water_cauldron',
    )),
    'HalfTransparentBlock': frozenset((
        'black_stained_glass', 'blue_ice', 'blue_stained_glass', 'brown_stained_glass', 'copper_grate',
        'cyan_stained_glass', 'exposed_copper_grate', 'frosted_ice', 'glass', 'gray_stained_glass',
        'green_stained_glass', 'honey_block', 'ice', 'light_blue_stained_glass', 'light_gray_stained_glass',
        'lime_stained_glass', 'magenta_stained_glass', 'orange_stained_glass', 'oxidized_copper_grate',
        'pink_stained_glass', 'purple_stained_glass', 'red_stained_glass', 'slime_block', 'tinted_glass',
        'waxed_copper_grate', 'waxed_exposed_copper_grate', 'waxed_oxidized_copper_grate',
        'waxed_weathered_copper_grate', 'weathered_copper_grate', 'white_stained_glass', 'yellow_stained_glass',
    )),
    'TransparentBlock': frozenset((
        'black_stained_glass', 'blue_stained_glass', 'brown_stained_glass', 'copper_grate', 'cyan_stained_glass',
        'exposed_copper_grate', 'glass', 'gray_stained_glass', 'green_stained_glass', 'light_blue_stained_glass',
        'light_gray_stained_glass', 'lime_stained_glass', 'magenta_stained_glass', 'orange_stained_glass',
        'oxidized_copper_grate', 'pink_stained_glass', 'purple_stained_glass', 'red_stained_glass', 'tinted_glass',
        'waxed_copper_grate', 'waxed_exposed_copper_grate', 'waxed_oxidized_copper_grate',
        'waxed_weathered_copper_grate', 'weathered_copper_grate', 'white_stained_glass', 'yellow_stained_glass',
    )),
    'SignBlock': frozenset((
        'acacia_hanging_sign', 'acacia_sign', 'acacia_wall_hanging_sign', 'acacia_wall_sign', 'bamboo_hanging_sign',
        'bamboo_sign', 'bamboo_wall_hanging_sign', 'bamboo_wall_sign', 'birch_hanging_sign', 'birch_sign',
        'birch_wall_hanging_sign', 'birch_wall_sign', 'cherry_hanging_sign', 'cherry_sign', 'cherry_wall_hanging_sign',
        'cherry_wall_sign', 'crimson_hanging_sign', 'crimson_sign', 'crimson_wall_hanging_sign', 'crimson_wall_sign',
        'dark_oak_hanging_sign', 'dark_oak_sign', 'dark_oak_wall_hanging_sign', 'dark_oak_wall_sign',
        'jungle_hanging_sign', 'jungle_sign', 'jungle_wall_hanging_sign', 'jungle_wall_sign', 'mangrove_hanging_sign',
        'mangrove_sign', 'mangrove_wall_hanging_sign', 'mangrove_wall_sign', 'oak_hanging_sign', 'oak_sign',
        'oak_wall_hanging_sign', 'oak_wall_sign', 'pale_oak_hanging_sign', 'pale_oak_sign',
        'pale_oak_wall_hanging_sign', 'pale_oak_wall_sign', 'poplar_hanging_sign', 'poplar_sign',
        'poplar_wall_hanging_sign', 'poplar_wall_sign', 'spruce_hanging_sign', 'spruce_sign',
        'spruce_wall_hanging_sign', 'spruce_wall_sign', 'warped_hanging_sign', 'warped_sign',
        'warped_wall_hanging_sign', 'warped_wall_sign',
    )),
    'ShelfBlock': frozenset((
        'acacia_shelf', 'bamboo_shelf', 'birch_shelf', 'cherry_shelf', 'crimson_shelf', 'dark_oak_shelf',
        'jungle_shelf', 'mangrove_shelf', 'oak_shelf', 'pale_oak_shelf', 'poplar_shelf', 'spruce_shelf',
        'warped_shelf',
    )),
    'AbstractChestBlock': frozenset((
        'chest', 'copper_chest', 'ender_chest', 'exposed_copper_chest', 'oxidized_copper_chest', 'trapped_chest',
        'waxed_copper_chest', 'waxed_exposed_copper_chest', 'waxed_oxidized_copper_chest',
        'waxed_weathered_copper_chest', 'weathered_copper_chest',
    )),
    'ShulkerBoxBlock': frozenset((
        'black_shulker_box', 'blue_shulker_box', 'brown_shulker_box', 'cyan_shulker_box', 'gray_shulker_box',
        'green_shulker_box', 'light_blue_shulker_box', 'light_gray_shulker_box', 'lime_shulker_box',
        'magenta_shulker_box', 'orange_shulker_box', 'pink_shulker_box', 'purple_shulker_box', 'red_shulker_box',
        'shulker_box', 'white_shulker_box', 'yellow_shulker_box',
    )),
    'AbstractBannerBlock': frozenset((
        'black_banner', 'black_wall_banner', 'blue_banner', 'blue_wall_banner', 'brown_banner', 'brown_wall_banner',
        'cyan_banner', 'cyan_wall_banner', 'gray_banner', 'gray_wall_banner', 'green_banner', 'green_wall_banner',
        'light_blue_banner', 'light_blue_wall_banner', 'light_gray_banner', 'light_gray_wall_banner', 'lime_banner',
        'lime_wall_banner', 'magenta_banner', 'magenta_wall_banner', 'orange_banner', 'orange_wall_banner',
        'pink_banner', 'pink_wall_banner', 'purple_banner', 'purple_wall_banner', 'red_banner', 'red_wall_banner',
        'white_banner', 'white_wall_banner', 'yellow_banner', 'yellow_wall_banner',
    )),
    'AbstractSkullBlock': frozenset((
        'creeper_head', 'creeper_wall_head', 'dragon_head', 'dragon_wall_head', 'piglin_head', 'piglin_wall_head',
        'player_head', 'player_wall_head', 'skeleton_skull', 'skeleton_wall_skull', 'wither_skeleton_skull',
        'wither_skeleton_wall_skull', 'zombie_head', 'zombie_wall_head',
    )),
    'BellBlock': frozenset((
        'bell',
    )),
    'ConduitBlock': frozenset((
        'conduit',
    )),
    'DecoratedPotBlock': frozenset((
        'decorated_pot',
    )),
    'EnchantingTableBlock': frozenset((
        'enchanting_table',
    )),
    'EndPortalBlock': frozenset((
        'end_portal',
    )),
    'EndGatewayBlock': frozenset((
        'end_gateway',
    )),
    'CopperGolemStatueBlock': frozenset((
        'copper_golem_statue', 'exposed_copper_golem_statue', 'oxidized_copper_golem_statue',
        'waxed_copper_golem_statue', 'waxed_exposed_copper_golem_statue', 'waxed_oxidized_copper_golem_statue',
        'waxed_weathered_copper_golem_statue', 'weathered_copper_golem_statue',
    )),
}
