#!/usr/bin/env python3
"""Генерирует engine/gen/mc_biome_names.h — единая нумерация биомов (объединение по всем версиям, по алфавиту).
Идентификаторы внутренние: тесты и файлы обмена используют имена, а не числа."""
import os, glob
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
names = set()
for d in glob.glob(f'{ROOT}/src/data-*/data/minecraft/worldgen/biome'):
    for f in os.listdir(d):
        if f.endswith('.json'):
            names.add(f[:-5])
names = sorted(names)
with open(f'{ROOT}/engine/gen/mc_biome_names.h', 'w') as f:
    f.write('/* generated by tools/gen_biome_names.py — не редактировать */\n#ifndef MC_BIOME_NAMES_H\n#define MC_BIOME_NAMES_H\n')
    f.write(f'#define MC_BIOME_COUNT {len(names)}\n')
    f.write('static const char *const MC_BIOME_NAMES[MC_BIOME_COUNT] = {\n')
    for n in names:
        f.write(f'    "{n}",\n')
    f.write('};\n#endif\n')
print(len(names), 'biomes')
